module.exports = {

  payment: [{
      item: 'Hotově na prodejně',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Dobírka',
      price: '30,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Bankovní převod',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Platební karta',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Platební brána Comgate',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Platební brána Gopay',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    }
  ],

  shipment: [{
      item: 'Osobní odběr',
      price: '0,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Česká pošta',
      price: '99,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'DPD',
      price: '119,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'DHL',
      price: '119,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Lokální kurýr',
      price: '89,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    },
    {
      item: 'Zásilkovna',
      price: '69,-',
      note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, nemo.'
    }
  ],

  lorem: [
    'Prožíváme-li delší dobu idylu, přestaneme ji vnímat, a osud by nám prokázal neocenitelnou službu, kdyby nás popadl za límec a vyhodil dočasně na mráz.',
    'Vy, kdož jste nad námi zvítězili, řekněte si sami pro sebe, že Babylon padl a že jeho stavby byly vyvráceny. Já vám přese všechno říkám, že člověk zůstává, aby byl souzen, každý na své vlastní lavici obžalovaných. Každý člověk je malá válka.',
    'Přijatelnost hodnot závisí vždy na jejich úspěchu. Každý, kdo se snaží dosáhnout falešné vyváženosti, destabilizuje společnost. Rozsudky musejí být váženy jen z toho hlediska, jaký mají význam pro udržení spořádané společnosti. Nesčetné dávné civilizace ztroskotaly právě na útesech spravedlnosti pro všechny. Taková pošetilost ničí přirozenou hierarchii, která je mnohem důležitější. Každý jedinec nabývá na významu jen ve vztahu k celé společnosti. Když společnost nebude uspořádána v logických krocích, nikdo v ní nemůže najít své místo - ani ten nejnižší, ani ten nejvyšší.',
    'Nesmím se bát. Strach zabíjí myšlení. Strach je malá smrt přinášející naprosté vyhlazení. Budu svému strachu čelit. Dovolím mu, aby prošel kolem mne a skrze mne. A až projde a zmizí, otočím se a podívám se, kudy šel. Tam, kam strach odešel, nic nezůstane. Zůstanu pouze já.',
    'V bytě jakýsi zvučný hlas předčítal řadu čísel, která měla cosi společného s výrobou šedé litiny. Hlas vycházel z obdélníkové desky, jakéhosi matného zrcadla, jež bylo součástí povrchu stěny po pravé straně. Winston otočil knoflíkem a hlas se trochu ztišil, ale slovům bylo stále ještě rozumět.',
    'Přístroj (ve skutečnosti televizní obrazovka) se dal ztlumit, ale nebylo možné ho úplně vypnout. Popošel k oknu: malá, křehká postava, jejíž vyzáblost ještě zvýrazňovala modrá kombinéze, stejnokroj Strany. Vlasy měl velmi světlé, tvář přirozeně ruměnou, pokožku zhrublou od drsného mýdla, tupých žiletek a chladu zimy, která právě skončila.',
    'Svět venku vypadal i přes zavřené okno studeně. Na ulici vítr vířil prach a útržky papíru, a třebaže svítilo slunko a obloha byla ostře modrá, zdálo se, jako by nic nemělo barvu kromě těch všudypřítomných plakátů.',
  ],

  lorem80: [
  'Prožíváme-li delší dobu idylu, přestaneme ji vnímat, a osud by nám prokázal.',
  'neocenitelnou službu, kdyby nás popadl za límec a vyhodil dočasně na mráz.',
  'Vy, kdož jste nad námi zvítězili, řekněte si sami pro sebe, že Babylon padl.',
  'A že jeho stavby byly vyvráceny. Já vám přese všechno říkám, že zůstává.',
  'Aby byl souzen, každý na své vlastní lavici obžalovaných. Každý je malá.',
  'Přijatelnost hodnot závisí vždy na jejich úspěchu. Každý, kdo se dosáhnout.',
  'Falešné vyváženosti, destabilizuje společnost. Rozsudky musejí být váženy jen.',
  'Z toho hlediska, jaký mají význam pro udržení spořádané společnosti.',
  'Nesčetné dávné civilizace ztroskotaly právě na útesech spravedlnosti všechny.',
  'Taková pošetilost ničí přirozenou hierarchii, která je mnohem důležitější.',
  'Každý jedinec nabývá na významu jen ve vztahu k celé společnosti.',
  'Když společnost nebude uspořádána v logických krocích, nikdo nemůže najít.',
  'Nesmím se bát. Strach zabíjí myšlení. Strach je malá přinášející naprosté.',
  'Budu svému strachu čelit. Dovolím mu, aby prošel kolem mne a skrze mne.',
  'A až projde a zmizí, otočím se a podívám se, kudy šel. Tam, strach odešel.',
  'V bytě jakýsi zvučný hlas předčítal řadu čísel, která měla cosi společného.',
  'Hlas vycházel z obdélníkové desky, jakéhosi matného zrcadla, jež součástí.',
  'Stěny po pravé straně. Winston otočil knoflíkem a hlas se trochu ztišil ještě.',
  'Přístroj (ve skutečnosti televizní obrazovka) se dal ztlumit, nebylo možné.',
  'Popošel k oknu: malá, křehká postava, jejíž vyzáblost zvýrazňovala modrá.',
  'Vlasy měl velmi světlé, tvář přirozeně ruměnou, pokožku zhrublou od mýdla.',
  'Svět venku vypadal i přes zavřené okno studeně. Na ulici vítr vířil prach.',
  'A třebaže svítilo slunko a obloha byla ostře modrá, zdálo se, jako by nic.'
  ],

  books: [
    'Enderova hra',
    'Mluvčí za mrtvé',
    'Xenocida',
    'Děti ducha',
    'Enderův stín',
    'Hegemonův stín',
    'Stínové loutky',
    'Marťanská kronika',
    '451 stupňů Fahrenheita',
    'Kaleidoskop',
    'Duna',
    'Den trifidů',
    'Dveře do léta',
    'Cizinec v cizí zemi',
    'Harry Potter a vězeň z Azkabanu',
    'Harry Potter a relikvie smrti',
    'Návrat krále',
    'Hra o trůny II',
    'Kmotr',
    'Bouře mečů II',
    'Harry Potter a princ dvojí krve',
    'Utekl jsem z Osvětimi',
    'Bouře mečů I',
    'Dva proti Říši',
    'Dvě věže',
    'Společenstvo prstenu',
    'Tajný závod',
    'Záskok',
    'Bouře mečů',
    'Hra o trůny',
    'Muži, kteří nenávidí ženy',
    'Harry Potter - Filmová kouzla',
    'Mengeleho děvče',
    'Rychlé šípy 2',
    'Rychlé šípy 4',
    'Velké dobrodružství Pepíka Střechy',
    'Harry Potter a Ohnivý pohár',
    'Hra o trůny I',
    'Rychlé šípy 1',
    'Střet králů II',
    '1984',
    'Dědečkové',
    'Hry a semináře',
    'Magie ničivá',
    'O zahradě',
    'Příběh umění',
    'Rychlé šípy 3',
    'Harry Potter a Kámen mudrců',
    'Šikmý kostel 2',
    'Slova paprsků',
    'Vačice, která se nesmála',
    'Zelená míle',
    'Zvíře',
    '20x Čtyřlístek',
    'Chromý bůh',
    'Deset malých černoušků',
    'Dvůr mlhy a hněvu',
    'Hobit',
    'Jeden z nás',
    'Justýnka a asistenční jednorožec',
    'Můra noční, předvánoční',
    'Rok v lese',
    'SAS příručka jak přežít',
    'Střet králů I',
    'Svědkové z továrny na smrt',
    'Únosce draků',
    'Věž vlaštovky',
    'Černobílý svět',
    'Coffey na míli',
    'Faja',
    'Harry Potter a Fénixův řád',
    'Malý princ',
    'Narodili se, aby přežili',
    'Potom',
    'Strach moudrého muže',
    'Střet králů',
    'Svědectví o životě v KLDR',
    'Svět včerejška',
    'Taková normální rodinka',
    'Toulky českou minulostí 1.',
    'Dlouhý, Široký a Krátkozraký',
    'Klid je síla, řek tatínek',
    'Křest ohněm',
    'Lovci kostí',
    'Na smrt',
    'Rychlé šípy 5',
    'Vzpomínky ledu',
    'Záhada hlavolamu',
    'Báječné příběhy Čtyřlístku',
    'Byl jednou jeden krtek',
    'Dobrodružství v temných uličkách',
    'Jeden za druhým',
    'Lovec přízraků',
    'Noční výprava',
    'O čertovi',
    'Peklo blízko nebe',
    'Záhada hlavolamu (komiks)',
    'Zloba',
    'Cesta králů',
    'Coffeyho ruce',
    'Doba z druhé ruky',
    'Krvavé země',
    'Maus II: A tady začalo moje trápení',
    'Meč osudu',
    'Naděje umírá poslední',
    'Není co závidět',
    'O klíči',
    'Rychlé šípy',
    'Řvi potichu, brácho',
    'Slavík'
  ],

  dekos: [
    'Kelímek papírový BIO-ECO BAMBOO 8oz 200/250ml',
    'Krabice na pizzu 32x32x3cm mvl bílá s potiskem PIZZA',
    'Miska PP 243x208x41/30mm 2-dílná černá s víkem PP transparentní',
    'Miska papírová na ovoce 500g, 180x100x83/105mm hnědá s potiskem',
    'Košík papírový na ovoce 2000g, 390x120x125mm hnědý s potiskem',
    'Víčko BIO z cukrové třtiny s otvorem na kelímek papírový 12-20oz 300-600ml bílé',
    'Sáček na hamburger S "Pure Paper" papír natur s odtrhem 15x8,5/8,5x16,5cm',
    'Kelímek papírový WRAP 100/110ml 4oz embossed černý 63mm',
    'Nůž dřevěný 16,5cm',
    'Burger box 185x145mm bílý',
    'Menubox 1-dílný, 2 zámkový bílý'
  ]

}


