module.exports = {

  books: [
    'Enderova hra',
    'Mluvčí za mrtvé',
    'Xenocida',
    'Děti ducha',
    'Enderův stín',
    'Hegemonův stín',
    'Stínové loutky',
    'Marťanská kronika',
    '451 stupňů Fahrenheita',
    'Kaleidoskop',
    'Duna',
    'Den trifidů',
    'Dveře do léta',
    'Cizinec v cizí zemi',
    'Harry Potter a vězeň z Azkabanu',
    'Harry Potter a relikvie smrti',
    'Návrat krále',
    'Hra o trůny II',
    'Kmotr',
    'Bouře mečů II',
    'Harry Potter a princ dvojí krve',
    'Utekl jsem z Osvětimi',
    'Bouře mečů I',
    'Dva proti Říši',
    'Dvě věže',
    'Společenstvo prstenu',
    'Tajný závod',
    'Záskok',
    'Bouře mečů',
    'Hra o trůny',
    'Muži, kteří nenávidí ženy',
    'Harry Potter - Filmová kouzla',
    'Mengeleho děvče',
    'Rychlé šípy 2',
    'Rychlé šípy 4',
    'Velké dobrodružství Pepíka Střechy',
    'Harry Potter a Ohnivý pohár',
    'Hra o trůny I',
    'Rychlé šípy 1',
    'Střet králů II',
    '1984',
    'Dědečkové',
    'Hry a semináře',
    'Magie ničivá',
    'O zahradě',
    'Příběh umění',
    'Rychlé šípy 3',
    'Harry Potter a Kámen mudrců',
    'Šikmý kostel 2',
    'Slova paprsků',
    'Vačice, která se nesmála',
    'Zelená míle',
    'Zvíře',
    '20x Čtyřlístek',
    'Chromý bůh',
    'Deset malých černoušků',
    'Dvůr mlhy a hněvu',
    'Hobit',
    'Jeden z nás',
    'Justýnka a asistenční jednorožec',
    'Můra noční, předvánoční',
    'Rok v lese',
    'SAS příručka jak přežít',
    'Střet králů I',
    'Svědkové z továrny na smrt',
    'Únosce draků',
    'Věž vlaštovky',
    'Černobílý svět',
    'Coffey na míli',
    'Faja',
    'Harry Potter a Fénixův řád',
    'Malý princ',
    'Narodili se, aby přežili',
    'Potom',
    'Strach moudrého muže',
    'Střet králů',
    'Svědectví o životě v KLDR',
    'Svět včerejška',
    'Taková normální rodinka',
    'Toulky českou minulostí 1.',
    'Dlouhý, Široký a Krátkozraký',
    'Klid je síla, řek tatínek',
    'Křest ohněm',
    'Lovci kostí',
    'Na smrt',
    'Rychlé šípy 5',
    'Vzpomínky ledu',
    'Záhada hlavolamu',
    'Báječné příběhy Čtyřlístku',
    'Byl jednou jeden krtek',
    'Dobrodružství v temných uličkách',
    'Jeden za druhým',
    'Lovec přízraků',
    'Noční výprava',
    'O čertovi',
    'Peklo blízko nebe',
    'Záhada hlavolamu (komiks)',
    'Zloba',
    'Cesta králů',
    'Coffeyho ruce',
    'Doba z druhé ruky',
    'Krvavé země',
    'Maus II: A tady začalo moje trápení',
    'Meč osudu',
    'Naděje umírá poslední',
    'Není co závidět',
    'O klíči',
    'Rychlé šípy',
    'Řvi potichu, brácho',
    'Slavík'
  ],

  dekos: [
    'Kelímek papírový BIO-ECO BAMBOO 8oz 200/250ml',
    'Krabice na pizzu 32x32x3cm mvl bílá s potiskem PIZZA',
    'Miska PP 243x208x41/30mm 2-dílná černá s víkem PP transparentní',
    'Miska papírová na ovoce 500g, 180x100x83/105mm hnědá s potiskem',
    'Košík papírový na ovoce 2000g, 390x120x125mm hnědý s potiskem',
    'Víčko BIO z cukrové třtiny s otvorem na kelímek papírový 12-20oz 300-600ml bílé',
    'Sáček na hamburger S "Pure Paper" papír natur s odtrhem 15x8,5/8,5x16,5cm',
    'Kelímek papírový WRAP 100/110ml 4oz embossed černý 63mm',
    'Nůž dřevěný 16,5cm',
    'Burger box 185x145mm bílý',
    'Menubox 1-dílný, 2 zámkový bílý'
  ]

}


